language: node_js
node_js:
  - '14'
before_install:
  - npm install -g yarn
  - pip install --user awscli
install:
  - yarn install
script:
  - yarn validate
notifications:
  email: false
deploy:
  provider: script
  script: ./scripts/publish.sh
  on:
    tags: true
    node: '10.16.3'
  skip_cleanup: true
env:
  global:
    - PATH: PATH=$HOME/.local/bin:$PATH
