# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Zapier Dev Platform CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint

  test-cli:
    runs-on:
      - ubuntu-latest
      - macos-11
      - windows-2022

    environment: ci
    env:
      ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_DEPLOY_KEY }}
      TEST_APP_ID: ${{ secrets.TEST_APP_ID }}

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Test
        run: yarn test
        working-directory: packages/cli

  test-core:
    runs-on: ubuntu-latest
    environment: ci
    env:
      ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_DEPLOY_KEY }}
      TEST_APP_ID: ${{ secrets.TEST_APP_ID }}

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Test
        run: yarn test
        working-directory: packages/core

  test-schema:
    runs-on: ubuntu-latest
    environment: ci
    env:
      ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_DEPLOY_KEY }}
      TEST_APP_ID: ${{ secrets.TEST_APP_ID }}

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Test
        run: yarn test
        working-directory: packages/schema

  smoke-test-cli:
    runs-on:
      - ubuntu-latest
      - macos-11
      - windows-2022

    environment: ci
    env:
      ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_DEPLOY_KEY }}
      TEST_APP_ID: ${{ secrets.TEST_APP_ID }}

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Test
        run: yarn smoke-test
        working-directory: packages/cli

  smoke-test-core:
    runs-on: ubuntu-latest
    environment: ci
    env:
      ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_DEPLOY_KEY }}
      TEST_APP_ID: ${{ secrets.TEST_APP_ID }}

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Test
        run: yarn smoke-test
        working-directory: packages/core

  smoke-test-schema:
    runs-on: ubuntu-latest
    environment: ci
    env:
      ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_DEPLOY_KEY }}
      TEST_APP_ID: ${{ secrets.TEST_APP_ID }}

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Test
        run: yarn smoke-test
        working-directory: packages/schema
